<?php

$icon_options = [
  [
    'value'     => 'announcement',
    'label'     => esc_html__( 'Announcement', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/announcement.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'book',
    'label'     => esc_html__( 'Book', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/book.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'briefcase',
    'label'     => esc_html__( 'Briefcase', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/briefcase.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'calander',
    'label'     => esc_html__( 'Calendar', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/calander.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'chat',
    'label'     => esc_html__( 'Chat', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/chat.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'check-circle',
    'label'     => esc_html__( 'Check circle', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/check-circle.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'clip',
    'label'     => esc_html__( 'Clip', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/clip.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'clock',
    'label'     => esc_html__( 'Clock', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/clock.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'cookie-black',
    'label'     => esc_html__( 'Cookie black', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/cookie-black.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'emotion-happy',
    'label'     => esc_html__( 'Emotion happy', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/emotion-happy.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'emotion-sad',
    'label'     => esc_html__( 'Emotion sad', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/emotion-sad.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'exclamation',
    'label'     => esc_html__( 'Exclamation', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/exclamation.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'heart',
    'label'     => esc_html__( 'Heart', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/heart.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'help',
    'label'     => esc_html__( 'Help', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/help.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'information',
    'label'     => esc_html__( 'Information', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/information.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'key',
    'label'     => esc_html__( 'Key', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/key.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'location',
    'label'     => esc_html__( 'Location', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/location.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'moon',
    'label'     => esc_html__( 'Moon', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/moon.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'music',
    'label'     => esc_html__( 'Music', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/music.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'notification',
    'label'     => esc_html__( 'Notification', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/notification.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'rocket',
    'label'     => esc_html__( 'Rocket', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/rocket.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'star',
    'label'     => esc_html__( 'Star', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/star.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'thumb-up',
    'label'     => esc_html__( 'Thumb up', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/thumb-up.svg',
    'image_set' => 'original',
  ],
  [
    'value'     => 'trophy',
    'label'     => esc_html__( 'Trophy', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/trophy.svg',
    'image_set' => 'original',
  ],
  // New Icons Below
  [
    'value'     => 'announcement-o',
    'label'     => esc_html__( 'Announcement', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/announcement-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'announcement-s',
    'label'     => esc_html__( 'Announcement', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/announcement-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'book-o',
    'label'     => esc_html__( 'Book', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/book-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'book-s',
    'label'     => esc_html__( 'Book', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/book-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'briefcase-o',
    'label'     => esc_html__( 'Briefcase', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/briefcase-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'briefcase-s',
    'label'     => esc_html__( 'Briefcase', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/briefcase-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'calendar-o',
    'label'     => esc_html__( 'Calendar', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/calendar-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'calendar-s',
    'label'     => esc_html__( 'Calendar', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/calendar-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'chat-o',
    'label'     => esc_html__( 'Chat', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/chat-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'chat-s',
    'label'     => esc_html__( 'Chat', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/chat-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'check-o',
    'label'     => esc_html__( 'Check circle', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/check-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'check-s',
    'label'     => esc_html__( 'Check circle', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/check-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'clip-o',
    'label'     => esc_html__( 'Clip', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/clip-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'clip-s',
    'label'     => esc_html__( 'Clip', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/clip-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'clock-o',
    'label'     => esc_html__( 'Clock', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/clock-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'clock-s',
    'label'     => esc_html__( 'Clock', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/clock-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'cookie-o',
    'label'     => esc_html__( 'Cookie', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/cookie-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'cookie-s',
    'label'     => esc_html__( 'Cookie', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/cookie-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'happy-o',
    'label'     => esc_html__( 'Emotion happy', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/happy-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'happy-s',
    'label'     => esc_html__( 'Emotion happy', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/happy-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'heart-o',
    'label'     => esc_html__( 'Heart', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/heart-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'heart-s',
    'label'     => esc_html__( 'Heart', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/heart-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'info-o',
    'label'     => esc_html__( 'Info', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/info-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'info-s',
    'label'     => esc_html__( 'Info', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/info-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'key-o',
    'label'     => esc_html__( 'Key', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/key-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'key-s',
    'label'     => esc_html__( 'Key', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/key-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'location-o',
    'label'     => esc_html__( 'Location', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/location-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'location-s',
    'label'     => esc_html__( 'Location', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/location-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'moon-o',
    'label'     => esc_html__( 'Moon', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/moon-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'moon-s',
    'label'     => esc_html__( 'Moon', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/moon-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'music-o',
    'label'     => esc_html__( 'Music', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/music-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'music-s',
    'label'     => esc_html__( 'Music', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/music-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'notification-o',
    'label'     => esc_html__( 'Notification', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/notification-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'notification-s',
    'label'     => esc_html__( 'Notification', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/notification-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'question-o',
    'label'     => esc_html__( 'Question', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/question-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'question-s',
    'label'     => esc_html__( 'Question', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/question-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'rocket-o',
    'label'     => esc_html__( 'Rocket', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/rocket-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'rocket-s',
    'label'     => esc_html__( 'Rocket', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/rocket-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'sad-o',
    'label'     => esc_html__( 'Sad', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/sad-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'sad-s',
    'label'     => esc_html__( 'Sad', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/sad-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'star-o',
    'label'     => esc_html__( 'Star', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/star-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'star-s',
    'label'     => esc_html__( 'Star', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/star-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'thumbsup-o',
    'label'     => esc_html__( 'Thumbs Up', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/thumbsup-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'thumbsup-s',
    'label'     => esc_html__( 'Thumbs Up', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/thumbsup-s.svg',
    'image_set' => 'solid',
  ],
  [
    'value'     => 'trophy-o',
    'label'     => esc_html__( 'Trophy', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/trophy-o.svg',
    'image_set' => 'outline',
  ],
  [
    'value'     => 'trophy-s',
    'label'     => esc_html__( 'Trophy', 'bulletinwp' ),
    'image_url' => $images_dir . '/icons/trophy-s.svg',
    'image_set' => 'solid',
  ]
];
